# Generated by Django 3.2.16 on 2023-01-17 14:57

from django.db import migrations, models

import imageupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("width", models.TextField()),
                ("height", models.TextField()),
                ("image_url", models.ImageField()),
            ],
        ),
    ]
