# Generated by Django 3.2.16 on 2023-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_rename_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='images',
            name='width',
            field=models.IntegerField(),
        ),
    ]
